export const KEY_BEACON_OUT_TIME = 'BEACON_OUT_TIME';
export const KEY_HISTORY_EXPIRED = 'HISTORY_DELETE_EXPIRED_HOUR';
export const KEY_NEW_BEACON_PREFIX = 'NEW_BEACON_PREFIX';
export const KEY_TEMP_WARN_C = 'TEMP_WARN_C';
export const KEY_TEMP_CRITICAL_C = 'TEMP_CRITICAL_C';

export const DEFAULT_BEACON_OUT_TIME = '30';
export const DEFAULT_HISTORY_EXPIRED_HOUR = '36';
export const DEFAULT_NEW_BEACON_PREFIX = '80ECCC0,80ECCB0';
export const DEFAULT_TEMP_WARN_C = '32';
export const DEFAULT_TEMP_CRITICAL_C = '36';

export const EDITABLE_PARAM_KEYS = [
  KEY_BEACON_OUT_TIME,
  KEY_HISTORY_EXPIRED,
  KEY_NEW_BEACON_PREFIX,
  KEY_TEMP_WARN_C,
  KEY_TEMP_CRITICAL_C,
];
